trigger:
  - master

pool:
  vmImage: "ubuntu-latest"
strategy:
  matrix:
    Python:
      python.version: "3.9"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "$(python.version)"
    displayName: "Use Python $(python.version)"

  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - script: conda env create --quiet --file ilamb.yml
    displayName: Create conda environment

  - script: |
      source activate ilamb
      python -m pip install ./
      python -c "import ILAMB; print('ILAMB v%s successfully installed' % (ILAMB.__version__))"
    displayName: "Install ILAMB"

  - script: |
      source activate ilamb
      cd test
      export RDMAV_FORK_SAFE=1
      export ILAMB_ROOT=./
      make
    displayName: "Run tests"
